name: ButtonWarp
main: com.codisimus.plugins.buttonwarp.ButtonWarp
version: 2.0.4
author: Codisimus
website: www.codisimus.com
description: Teleport using buttons with price/reward/custom messages
depend: [Vault]
startup: postworld
commands:
  buttonwarp:
    description: Used to setup and manage Warps
    usage: /<command> help
    aliases: [bw]
permissions:
  buttonwarp.use:
    description: Needed to activate a Warp
  buttonwarp.commandwarp:
    description: Needed to Warp by command
  buttonwarp.getreward:
    description: Needed to receive money from a Warp
  buttonwarp.freewarp:
    description: Use any Warp free of charge
  buttonwarp.make:
    description: Needed to create a Warp (/bw make)
  buttonwarp.move:
    description: Needed to move the destination of a Warp (/bw move)
  buttonwarp.link:
    description: Needed to link a Block to a Warp (/bw link)
  buttonwarp.unlink:
    description: Needed to unlink a Block to a Warp (/bw unlink)
  buttonwarp.delete:
    description: Needed to delete a Warp (/bw delete)
  buttonwarp.cost:
    description: Needed to set the amount of money taken when using a Warp (/bw cost)
  buttonwarp.reward:
    description: Needed to set the amount of money given when using a Warp (/bw reward)
  buttonwarp.access:
    description: Needed to set who has access to a Warp (/bw access)
  buttonwarp.source:
    description: Needed to set the source of money given/taken when using a Warp (/bw source)
  buttonwarp.cmd:
    description: Needed to add or remove commands to a Warp (/bw cmd)
  buttonwarp.msg:
    description: Needed to set the msg sent by a Warp (/bw msg)
  buttonwarp.time:
    description: Needed to set the reset time of a Warp (/bw time)
  buttonwarp.type:
    description: Needed to set the reset type of a Warp (/bw type)
  buttonwarp.max:
    description: Needed to set the maximum uses of a Warp Button (/bw max)
  buttonwarp.allow:
    description: Needed to set that items can be taken while warping (/bw allow)
  buttonwarp.deny:
    description: Needed to set that items cannt be taken while warping (/bw deny)
  buttonwarp.reset:
    description: Needed to reset activation times of a Warp (/bw reset)
  buttonwarp.list:
    description: Needed to list all Warps (/bw list)
  buttonwarp.info:
    description: Needed to list information about a Warp (/bw info)
  buttonwarp.rl:
    description: Needed to reload the plugin (/bw rl)
  buttonwarp.admin:
    description: Needed to break linked Blocks