name: ButtonWarp
main: ButtonWarp.ButtonWarp
version: 1.2.1
author: Codisimus
website: www.codisimus.com
description: Teleport using buttons with price/reward/custom messages
commands:
  buttonwarp:
    alias: bw
    description: Main command, type for additional help/commands